name: Build Debug APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build_debug_apk:
    name: Build Debug APK
    runs-on: ubuntu-latest
    env:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Create google-services.json
        run: |
          echo "Creating google-services.json..."
          if [ -n "$GOOGLE_SERVICES_JSON" ]; then
            echo "$GOOGLE_SERVICES_JSON" > app/google-services.json
            echo "google-services.json created from secret."
          else
            echo "GOOGLE_SERVICES_JSON secret not found. Using dummy file."
            cat .github/dummy-google-services.json > app/google-services.json
          fi

      - name: Debug file system
        run: |
          echo "--- Verifying google-services.json content ---"
          cat app/google-services.json
          echo "--- Verifying directory structure (app/) ---"
          ls -l app/

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
      
      - name: Upload Build Reports on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-build-reports
          path: app/build/reports/
          retention-days: 7 